-- Seed public.master_mapping with the canonical charge taxonomy.
-- Each INSERT uses ON CONFLICT (carrier, charge_description) DO UPDATE so this is idempotent;
-- safe to run even when rows already exist.


INSERT INTO public.master_mapping (carrier, charge_description, transportation_mode, category_1, category_2, category_3, category_4, category_5, standardized_charge)
VALUES
('UPS', '2nd Day Air A.M. Commercial', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', '2nd Day Air', '2nd Day Air Commercial', '2nd Day Air Commercial'),
('UPS', '2nd Day Air A.M. Commercial Third Party', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', '2nd Day Air', '2nd Day Air Commercial', '2nd Day Air Commercial'),
('UPS', '2nd Day Air Commercial', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', '2nd Day Air', '2nd Day Air Commercial', '2nd Day Air Commercial'),
('UPS', '2nd Day Air Commercial Collect', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', '2nd Day Air', '2nd Day Air Commercial', '2nd Day Air Commercial'),
('UPS', '2nd Day Air Commercial Third Party', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', '2nd Day Air', '2nd Day Air Commercial', '2nd Day Air Commercial'),
('UPS', '2nd Day Air Hundredweight Third Party', 'LTL', 'Base Freight', 'LTL / Hundredweight', 'LTL Freight', 'LTL (Hundredweight)', '2nd Day Air Other', '2nd Day Air Commercial'),
('UPS', '2nd Day Air Residential', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', '2nd Day Air', '2nd Day Air Residential', '2nd Day Air Residential'),
('UPS', '2nd Day Air Residential Third Party', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', '2nd Day Air', '2nd Day Air Residential', '2nd Day Air Residential'),
('UPS', '3 Day Select Commercial', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', '3 Day Select', '3 Day Commercial', '3 Day Select'),
('UPS', '3 Day Select Commercial Collect', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', '3 Day Select', '3 Day Commercial', '3 Day Select'),
('UPS', '3 Day Select Commercial Third Party', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', '3 Day Select', '3 Day Commercial', '3 Day Select'),
('UPS', '3 Day Select Hundredweight', 'LTL', 'Base Freight', 'LTL / Hundredweight', 'LTL Freight', 'LTL (Hundredweight)', '3Day Hundredweight', '3 Day Select'),
('UPS', '3 Day Select Hundredweight Third Party', 'LTL', 'Base Freight', 'LTL / Hundredweight', 'LTL Freight', 'LTL (Hundredweight)', '3Day Hundredweight', '3 Day Select'),
('UPS', '3 Day Select Residential', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', '3 Day Select', '3 Day Residential', '3 Day Select'),
('UPS', '3 Day Select Residential Third Party', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', '3 Day Select', '3 Day Residential', '3 Day Select'),
('UPS', '3 Day Select Undeliverable Return', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', '3 Day Select', 'Returns', '3 Day Select'),
('UPS', 'Additional Handling', 'Other', 'Accessorial Surcharge', 'Handling', 'Other / Penalties', 'Handling & Size', 'Additional Handling', 'Additional Handling'),
('UPS', 'Additional Handling - Length+Girth', 'Other', 'Accessorial Surcharge', 'Handling', 'Other / Penalties', 'Handling & Size', 'Additional Handling', 'Additional Handling'),
('UPS', 'Addl. Handling longest side', 'Other', 'Accessorial Surcharge', 'Handling', 'Other / Penalties', 'Handling & Size', 'Additional Handling', 'Additional Handling'),
('UPS', 'Addl. Handling weight', 'Other', 'Accessorial Surcharge', 'Handling', 'Other / Penalties', 'Handling & Size', 'Additional Handling', 'Additional Handling'),
('UPS', 'Address Correction', 'Other', 'Other / Penalties', 'Other Admin', 'Other / Penalties', 'Address Errors', 'Address Correction', 'Address Correction'),
('UPS', 'Address Correction 2nd Day Air', 'Other', 'Base Freight', 'Other Admin', 'Base Freight', '2nd Day Air', 'Address Correction', 'Address Correction'),
('UPS', 'Address Correction 3 Day Select', 'Other', 'Base Freight', 'Other Admin', 'Base Freight', '3 Day Select', 'Address Correction', 'Address Correction'),
('UPS', 'Address Correction Fuel Surcharge', 'Other', 'Fuel Surcharge', 'Other Admin', 'Fuel Surcharge', 'Fuel Surcharge', 'Address Correction', 'Fuel Surcharge'),
('UPS', 'Address Correction Ground', 'Other', 'Base Freight', 'Other Admin', 'Base Freight', 'Ground', 'Address Correction', 'Address Correction'),
('UPS', 'Address Correction Next Day Air', 'Other', 'Base Freight', 'Other Admin', 'Base Freight', 'Next Day Air', 'Address Correction', 'Address Correction'),
('UPS', 'Address Correction Next Day Air Early', 'Other', 'Base Freight', 'Other Admin', 'Base Freight', 'Next Day Air', 'Address Correction', 'Address Correction'),
('UPS', 'Address Correction Next Day Air Saver', 'Other', 'Base Freight', 'Other Admin', 'Base Freight', 'Next Day Air', 'Address Correction', 'Address Correction'),
('UPS', 'Adult Signature Required', 'Other', 'Accessorial Surcharge', 'Miscellaneous', 'Accessorials', 'Other Unclassified', 'Address Correction', 'Signature Required'),
('UPS', 'Billing Adjustment for  W/E 01/03/2026', 'Other', 'Other / Penalties', 'Other Admin', 'Other / Penalties', 'Adjustments', 'Billing Adjustment', 'Billing Adjustment'),
('UPS', 'Billing Adjustment for  W/E 01/10/2026', 'Other', 'Other / Penalties', 'Other Admin', 'Other / Penalties', 'Adjustments', 'Billing Adjustment', 'Billing Adjustment'),
('UPS', 'Billing Adjustment for  W/E 01/17/2026', 'Other', 'Other / Penalties', 'Other Admin', 'Other / Penalties', 'Adjustments', 'Billing Adjustment', 'Billing Adjustment'),
('UPS', 'Billing Adjustment for  W/E 06/07/2025', 'Other', 'Other / Penalties', 'Other Admin', 'Other / Penalties', 'Adjustments', 'Billing Adjustment', 'Billing Adjustment'),
('UPS', 'Billing Adjustment for  W/E 06/14/2025', 'Other', 'Other / Penalties', 'Other Admin', 'Other / Penalties', 'Adjustments', 'Billing Adjustment', 'Billing Adjustment'),
('UPS', 'Billing Adjustment for  W/E 06/21/2025', 'Other', 'Other / Penalties', 'Other Admin', 'Other / Penalties', 'Adjustments', 'Billing Adjustment', 'Billing Adjustment'),
('UPS', 'Billing Adjustment for  W/E 06/28/2025', 'Other', 'Other / Penalties', 'Other Admin', 'Other / Penalties', 'Adjustments', 'Billing Adjustment', 'Billing Adjustment'),
('UPS', 'Billing Adjustment for  W/E 07/19/2025', 'Other', 'Other / Penalties', 'Other Admin', 'Other / Penalties', 'Adjustments', 'Billing Adjustment', 'Billing Adjustment'),
('UPS', 'Billing Adjustment for  W/E 07/26/2025', 'Other', 'Other / Penalties', 'Other Admin', 'Other / Penalties', 'Adjustments', 'Billing Adjustment', 'Billing Adjustment'),
('UPS', 'Billing Adjustment for  W/E 08/09/2025', 'Other', 'Other / Penalties', 'Other Admin', 'Other / Penalties', 'Adjustments', 'Billing Adjustment', 'Billing Adjustment'),
('UPS', 'Billing Adjustment for  W/E 08/16/2025', 'Other', 'Other / Penalties', 'Other Admin', 'Other / Penalties', 'Adjustments', 'Billing Adjustment', 'Billing Adjustment'),
('UPS', 'Billing Adjustment for  W/E 08/23/2025', 'Other', 'Other / Penalties', 'Other Admin', 'Other / Penalties', 'Adjustments', 'Billing Adjustment', 'Billing Adjustment'),
('UPS', 'Billing Adjustment for  W/E 08/30/2025', 'Other', 'Other / Penalties', 'Other Admin', 'Other / Penalties', 'Adjustments', 'Billing Adjustment', 'Billing Adjustment'),
('UPS', 'Billing Adjustment for  W/E 09/06/2025', 'Other', 'Other / Penalties', 'Other Admin', 'Other / Penalties', 'Adjustments', 'Billing Adjustment', 'Billing Adjustment'),
('UPS', 'Billing Adjustment for  W/E 09/13/2025', 'Other', 'Other / Penalties', 'Other Admin', 'Other / Penalties', 'Adjustments', 'Billing Adjustment', 'Billing Adjustment'),
('UPS', 'Billing Adjustment for  W/E 09/20/2025', 'Other', 'Other / Penalties', 'Other Admin', 'Other / Penalties', 'Adjustments', 'Billing Adjustment', 'Billing Adjustment')
ON CONFLICT (carrier, charge_description) DO UPDATE SET
  transportation_mode = EXCLUDED.transportation_mode,
  category_1 = EXCLUDED.category_1,
  category_2 = EXCLUDED.category_2,
  category_3 = EXCLUDED.category_3,
  category_4 = EXCLUDED.category_4,
  category_5 = EXCLUDED.category_5,
  standardized_charge = EXCLUDED.standardized_charge;

INSERT INTO public.master_mapping (carrier, charge_description, transportation_mode, category_1, category_2, category_3, category_4, category_5, standardized_charge)
VALUES
('UPS', 'Billing Adjustment for  W/E 09/27/2025', 'Other', 'Other / Penalties', 'Other Admin', 'Other / Penalties', 'Adjustments', 'Billing Adjustment', 'Billing Adjustment'),
('UPS', 'Billing Adjustment for  W/E 10/04/2025', 'Other', 'Other / Penalties', 'Other Admin', 'Other / Penalties', 'Adjustments', 'Billing Adjustment', 'Billing Adjustment'),
('UPS', 'Billing Adjustment for  W/E 10/11/2025', 'Other', 'Other / Penalties', 'Other Admin', 'Other / Penalties', 'Adjustments', 'Billing Adjustment', 'Billing Adjustment'),
('UPS', 'Billing Adjustment for  W/E 10/18/2025', 'Other', 'Other / Penalties', 'Other Admin', 'Other / Penalties', 'Adjustments', 'Billing Adjustment', 'Billing Adjustment'),
('UPS', 'Billing Adjustment for  W/E 10/25/2025', 'Other', 'Other / Penalties', 'Other Admin', 'Other / Penalties', 'Adjustments', 'Billing Adjustment', 'Billing Adjustment'),
('UPS', 'Billing Adjustment for  W/E 11/08/2025', 'Other', 'Other / Penalties', 'Other Admin', 'Other / Penalties', 'Adjustments', 'Billing Adjustment', 'Billing Adjustment'),
('UPS', 'Billing Adjustment for  W/E 11/15/2025', 'Other', 'Other / Penalties', 'Other Admin', 'Other / Penalties', 'Adjustments', 'Billing Adjustment', 'Billing Adjustment'),
('UPS', 'Billing Adjustment for  W/E 11/22/2025', 'Other', 'Other / Penalties', 'Other Admin', 'Other / Penalties', 'Adjustments', 'Billing Adjustment', 'Billing Adjustment'),
('UPS', 'Billing Adjustment for  W/E 11/29/2025', 'Other', 'Other / Penalties', 'Other Admin', 'Other / Penalties', 'Adjustments', 'Billing Adjustment', 'Billing Adjustment'),
('UPS', 'Billing Adjustment for  W/E 12/06/2025', 'Other', 'Other / Penalties', 'Other Admin', 'Other / Penalties', 'Adjustments', 'Billing Adjustment', 'Billing Adjustment'),
('UPS', 'Billing Adjustment for  W/E 12/13/2025', 'Other', 'Other / Penalties', 'Other Admin', 'Other / Penalties', 'Adjustments', 'Billing Adjustment', 'Billing Adjustment'),
('UPS', 'Billing Adjustment for  W/E 12/20/2025', 'Other', 'Other / Penalties', 'Other Admin', 'Other / Penalties', 'Adjustments', 'Billing Adjustment', 'Billing Adjustment'),
('UPS', 'Billing Adjustment for  W/E 12/27/2025', 'Other', 'Other / Penalties', 'Other Admin', 'Other / Penalties', 'Adjustments', 'Billing Adjustment', 'Billing Adjustment'),
('UPS', 'Chargeback Addl. Handling weight', 'Other', 'Accessorial Surcharge', 'Handling', 'Other / Penalties', 'Handling & Size', 'Other/Unclassified', 'Additional Handling'),
('UPS', 'Chargeback Chargeback Surcharge', 'Other', 'Other / Penalties', 'Miscellaneous', 'Other / Penalties', 'Other Unclassified', 'Other/Unclassified', 'Admin Fee'),
('UPS', 'Chargeback Delivery Area Surcharge', 'Other', 'Accessorial Surcharge', 'Area Surcharge', 'Accessorials', 'Delivery Area', 'Other/Unclassified', 'Delivery Area Surcharge'),
('UPS', 'Chargeback Fuel Surcharge', 'Other', 'Fuel Surcharge', 'Fuel Surcharge', 'Fuel Surcharge', 'Fuel Surcharge', 'Other/Unclassified', 'Fuel Surcharge'),
('UPS', 'Chargeback Ground Commercial', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Ground', 'Other/Unclassified', 'Ground Commercial'),
('UPS', 'Commercial Adjustment', 'Other', 'Other / Penalties', 'Other Admin', 'Other / Penalties', 'Other Unclassified', 'Other', 'Discount'),
('UPS', 'Declared Value', 'Other', 'Other / Penalties', 'Miscellaneous', 'Other / Penalties', 'Other Unclassified', 'Other', 'Declared Value'),
('UPS', 'Delivery Area Surcharge', 'Other', 'Accessorial Surcharge', 'Area Surcharge', 'Accessorials', 'Delivery Area', 'DAS', 'Delivery Area Surcharge'),
('UPS', 'Delivery Area Surcharge - Extended', 'Other', 'Accessorial Surcharge', 'Area Surcharge', 'Accessorials', 'Delivery Area', 'DAS', 'Delivery Area Surcharge Extended'),
('UPS', 'Delivery Area Surcharge - Extended Adjustment', 'Other', 'Accessorial Surcharge', 'Other Admin', 'Accessorials', 'Delivery Area', 'DAS', 'Delivery Area Surcharge Extended'),
('UPS', 'Delivery Area Surcharge Adjustment', 'Other', 'Accessorial Surcharge', 'Other Admin', 'Accessorials', 'Delivery Area', 'DAS', 'Delivery Area Surcharge'),
('UPS', 'Delivery Confirmation Signature', 'Other', 'Accessorial Surcharge', 'Miscellaneous', 'Accessorials', 'Other Unclassified', 'Delivery Confirmation', 'Signature Required'),
('UPS', 'Delivery Confirmation Signature - Commercial', 'Other', 'Accessorial Surcharge', 'Miscellaneous', 'Accessorials', 'Other Unclassified', 'Delivery Confirmation', 'Signature Required'),
('UPS', 'Demand Surcharge - Commercial', 'Other', 'Other / Penalties', 'Peak/Demand', 'Other / Penalties', 'Other Unclassified', 'Other', 'Demand Surcharge'),
('UPS', 'Demand Surcharge - Commercial Adjustment', 'Other', 'Other / Penalties', 'Other Admin', 'Other / Penalties', 'Other Unclassified', 'Other', 'Demand Surcharge'),
('UPS', 'Demand Surcharge - Residential', 'Other', 'Accessorial Surcharge', 'Residential Surcharge', 'Accessorials', 'Residential', 'Other', 'Demand Surcharge'),
('UPS', 'Demand Surcharge - Residential Adjustment', 'Other', 'Accessorial Surcharge', 'Other Admin', 'Accessorials', 'Residential', 'Other', 'Demand Surcharge'),
('UPS', 'Demand Surcharge Addl Handling', 'Other', 'Accessorial Surcharge', 'Handling', 'Other / Penalties', 'Handling & Size', 'Other', 'Demand Surcharge'),
('UPS', 'Demand Surcharge Large Package', 'Other', 'Other / Penalties', 'Peak/Demand', 'Other / Penalties', 'Handling & Size', 'Other', 'Demand Surcharge'),
('UPS', 'Demand Surcharge-Addl Handling', 'Other', 'Accessorial Surcharge', 'Handling', 'Other / Penalties', 'Handling & Size', 'Other', 'Demand Surcharge'),
('UPS', 'Direct Delivery Only', 'Other', 'Other / Penalties', 'Miscellaneous', 'Other / Penalties', 'Other Unclassified', 'Other', 'Special Delivery'),
('UPS', 'Duty and Tax Forwarding Surcharge', 'Other', 'Other / Penalties', 'Miscellaneous', 'Other / Penalties', 'Other Unclassified', 'Other', 'Customs & Duties'),
('UPS', 'Early Surcharge', 'Other', 'Other / Penalties', 'Miscellaneous', 'Other / Penalties', 'Other Unclassified', 'Other', 'Early Surcharge'),
('UPS', 'Fuel Surcharge', 'Other', 'Fuel Surcharge', 'Fuel Surcharge', 'Fuel Surcharge', 'Fuel Surcharge', 'Other', 'Fuel Surcharge'),
('UPS', 'Fuel Surcharge Adjustment', 'Other', 'Fuel Surcharge', 'Other Admin', 'Fuel Surcharge', 'Fuel Surcharge', 'Other', 'Fuel Surcharge'),
('UPS', 'Future Day Pickup - Alternate Address - Phone Request', 'Other', 'Other / Penalties', 'Miscellaneous', 'Other / Penalties', 'Other Unclassified', 'Other', 'Reroute / Intercept'),
('UPS', 'Ground Commercial', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Ground', 'Ground Commercial', 'Ground Commercial'),
('UPS', 'Ground Commercial Collect', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Ground', 'Ground Commercial', 'Ground Commercial'),
('UPS', 'Ground Commercial Third Party', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Ground', 'Ground Commercial', 'Ground Commercial'),
('UPS', 'Ground Commercial UPS Delivery Intercept', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Ground', 'Ground Commercial', 'Reroute / Intercept'),
('UPS', 'Ground Commercial UPS Delivery Intercept Collect', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Ground', 'Ground Commercial', 'Ground Commercial'),
('UPS', 'Ground Commercial UPS Delivery Intercept Third Party', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Ground', 'Ground Commercial', 'Ground Commercial')
ON CONFLICT (carrier, charge_description) DO UPDATE SET
  transportation_mode = EXCLUDED.transportation_mode,
  category_1 = EXCLUDED.category_1,
  category_2 = EXCLUDED.category_2,
  category_3 = EXCLUDED.category_3,
  category_4 = EXCLUDED.category_4,
  category_5 = EXCLUDED.category_5,
  standardized_charge = EXCLUDED.standardized_charge;

INSERT INTO public.master_mapping (carrier, charge_description, transportation_mode, category_1, category_2, category_3, category_4, category_5, standardized_charge)
VALUES
('UPS', 'Ground Hundredweight', 'LTL', 'Base Freight', 'LTL / Hundredweight', 'LTL Freight', 'LTL (Hundredweight)', 'Ground Hundredweight', 'Ground Commercial'),
('UPS', 'Ground Hundredweight Third Party', 'LTL', 'Base Freight', 'LTL / Hundredweight', 'LTL Freight', 'LTL (Hundredweight)', 'Ground Hundredweight', 'Ground Commercial'),
('UPS', 'Ground Residential', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Ground', 'Ground Residential', 'Ground Residential'),
('UPS', 'Ground Residential Collect', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Ground', 'Ground Residential', 'Ground Residential'),
('UPS', 'Ground Residential Third Party', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Ground', 'Ground Residential', 'Ground Residential'),
('UPS', 'Ground Return to Sender', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Returns', 'Returns', 'Returns'),
('UPS', 'Ground Return to Sender Third Party', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Returns', 'Returns', 'Returns'),
('UPS', 'Ground Shipment Third Party', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Ground', 'Ground Other', 'Ground Commercial'),
('UPS', 'Ground Undeliverable Return', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Returns', 'Returns', 'Returns'),
('UPS', 'GSR Delivery Area Surcharge', 'Other', 'Accessorial Surcharge', 'Area Surcharge', 'Accessorials', 'Delivery Area', 'GSR', 'Delivery Area Surcharge'),
('UPS', 'GSR Demand Surcharge - Commercial', 'Other', 'Other / Penalties', 'Peak/Demand', 'Other / Penalties', 'Other Unclassified', 'GSR', 'Demand Surcharge'),
('UPS', 'GSR Early Surcharge', 'Other', 'Other / Penalties', 'Miscellaneous', 'Other / Penalties', 'Other Unclassified', 'GSR', 'Early Surcharge'),
('UPS', 'GSR Next Day Air Commercial', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Next Day Air', 'GSR', 'Next Day Air Commercial'),
('UPS', 'GSR Next Day Air Commercial Collect', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Next Day Air', 'GSR', 'Next Day Air Commercial'),
('UPS', 'GSR Next Day Air Commercial Third Party', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Next Day Air', 'GSR', 'Next Day Air Commercial'),
('UPS', 'GSR Next Day Air Early Commercial Third Party', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Next Day Air', 'GSR', 'Next Day Air Early'),
('UPS', 'GSR Next Day Air Residential', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Next Day Air', 'GSR', 'Next Day Air Residential'),
('UPS', 'GSR Residential Surcharge', 'Other', 'Accessorial Surcharge', 'Residential Surcharge', 'Accessorials', 'Residential', 'GSR', 'Residential Surcharge'),
('UPS', 'GSR Shipping Charge Correction', 'Other', 'Other / Penalties', 'Other Admin', 'Other / Penalties', 'Adjustments', 'GSR', 'Shipping Charge Correction'),
('UPS', 'GSR Zone Adjustment', 'Other', 'Other / Penalties', 'Other Admin', 'Other / Penalties', 'Other Unclassified', 'GSR', 'Zone Adjustment'),
('UPS', 'Large Package Surcharge - Length + Girth', 'Other', 'Other / Penalties', 'Large Package', 'Other / Penalties', 'Handling & Size', 'Large Package', 'Large Package Surcharge'),
('UPS', 'Large Package Surcharge Comm - Length', 'Other', 'Other / Penalties', 'Large Package', 'Other / Penalties', 'Handling & Size', 'Large Package', 'Large Package Surcharge'),
('UPS', 'Next Day Air Commercial', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Next Day Air', 'Next Day Air Commercial', 'Next Day Air Commercial'),
('UPS', 'Next Day Air Commercial Collect', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Next Day Air', 'Next Day Air Commercial', 'Next Day Air Commercial'),
('UPS', 'Next Day Air Commercial Third Party', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Next Day Air', 'Next Day Air Commercial', 'Next Day Air Commercial'),
('UPS', 'Next Day Air Early Commercial', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Next Day Air', 'Next Day Air Early Commercial', 'Next Day Air Early'),
('UPS', 'Next Day Air Early Commercial Collect', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Next Day Air', 'Next Day Air Early Commercial', 'Next Day Air Early'),
('UPS', 'Next Day Air Early Commercial Third Party', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Next Day Air', 'Next Day Air Early Commercial', 'Next Day Air Early'),
('UPS', 'Next Day Air Early Residential', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Next Day Air', 'Next Day Air Early Residential', 'Next Day Air Early'),
('UPS', 'Next Day Air Early Residential Third Party', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Next Day Air', 'Next Day Air Early Residential', 'Next Day Air Early'),
('UPS', 'Next Day Air Hundredweight Third Party', 'LTL', 'Base Freight', 'LTL / Hundredweight', 'LTL Freight', 'LTL (Hundredweight)', 'Next Day Air Early Residential', 'Next Day Air Commercial'),
('UPS', 'Next Day Air Residential', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Next Day Air', 'Next Day Air Residential', 'Next Day Air Residential'),
('UPS', 'Next Day Air Residential Collect', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Next Day Air', 'Next Day Air Residential', 'Next Day Air Residential'),
('UPS', 'Next Day Air Residential Third Party', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Next Day Air', 'Next Day Air Residential', 'Next Day Air Residential'),
('UPS', 'Next Day Air Saver Commercial', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Next Day Air', 'Next Day Air Saver Commercial', 'Next Day Air Saver'),
('UPS', 'Next Day Air Saver Commercial Third Party', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Next Day Air', 'Next Day Air Saver Commercial', 'Next Day Air Saver'),
('UPS', 'Next Day Air Saver Hundredweight Third Party', 'LTL', 'Base Freight', 'LTL / Hundredweight', 'LTL Freight', 'LTL (Hundredweight)', 'Next Day Air Saver Hundredweight', 'Next Day Air Saver'),
('UPS', 'Next Day Air Saver Residential', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Next Day Air', 'Next Day Air Saver Residential', 'Next Day Air Saver'),
('UPS', 'Next Day Air Saver Residential Third Party', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Next Day Air', 'Next Day Air Saver Residential', 'Next Day Air Saver'),
('UPS', 'Not Previously Billed 2nd Day Air A.M. Commercial', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', '2nd Day Air', '2nd Day Air Commercial', '2nd Day Air Commercial'),
('UPS', 'Not Previously Billed Canada Residential Surcharge', 'Other', 'Base Freight', 'International', 'Accessorials', 'Residential', 'International', 'Residential Surcharge'),
('UPS', 'Not Previously Billed Fuel Surcharge', 'Other', 'Fuel Surcharge', 'Fuel Surcharge', 'Fuel Surcharge', 'Fuel Surcharge', 'Fuel', 'Fuel Surcharge'),
('UPS', 'Not Previously Billed Missing PLD Fee', 'Other', 'Other / Penalties', 'Miscellaneous', 'Other / Penalties', 'Other Unclassified', 'Other', 'Admin Fee'),
('UPS', 'Not Previously Billed Surge Fee - Com', 'Other', 'Other / Penalties', 'Peak/Demand', 'Other / Penalties', 'Other Unclassified', 'Other', 'Surge Fee'),
('UPS', 'Not Previously Billed Surge Fee - Resi', 'Other', 'Other / Penalties', 'Residential Surcharge', 'Other / Penalties', 'Other Unclassified', 'Other', 'Surge Fee')
ON CONFLICT (carrier, charge_description) DO UPDATE SET
  transportation_mode = EXCLUDED.transportation_mode,
  category_1 = EXCLUDED.category_1,
  category_2 = EXCLUDED.category_2,
  category_3 = EXCLUDED.category_3,
  category_4 = EXCLUDED.category_4,
  category_5 = EXCLUDED.category_5,
  standardized_charge = EXCLUDED.standardized_charge;

INSERT INTO public.master_mapping (carrier, charge_description, transportation_mode, category_1, category_2, category_3, category_4, category_5, standardized_charge)
VALUES
('UPS', 'Not Previously Billed Third Party Billing Service', 'Other', 'Other / Penalties', 'Other Admin', 'Accessorials', 'Other Unclassified', 'Other', 'Third Party Billing'),
('UPS', 'Paper Commercial Invoice Surcharge', 'Other', 'Other / Penalties', 'Miscellaneous', 'Other / Penalties', 'Other Unclassified', 'Other', 'Service / Admin Fee'),
('UPS', 'Payment Processing Fee', 'Other', 'Other / Penalties', 'Miscellaneous', 'Other / Penalties', 'Other Unclassified', 'Other', 'Service / Admin Fee'),
('UPS', 'Remote Area Surcharge', 'Other', 'Accessorial Surcharge', 'Area Surcharge', 'Other / Penalties', 'Delivery Area', 'Other', 'Remote Area Surcharge'),
('UPS', 'Reroute - Phone Request', 'Other', 'Other / Penalties', 'Miscellaneous', 'Other / Penalties', 'Address Errors', 'Other', 'Reroute / Intercept'),
('UPS', 'Reroute - Web Request', 'Other', 'Other / Penalties', 'Miscellaneous', 'Other / Penalties', 'Address Errors', 'Other', 'Reroute / Intercept'),
('UPS', 'Reschedule Delivery - Web Request', 'Other', 'Other / Penalties', 'Miscellaneous', 'Other / Penalties', 'Other Unclassified', 'Other', 'Reroute / Intercept'),
('UPS', 'Residential Adjustment', 'Other', 'Accessorial Surcharge', 'Other Admin', 'Accessorials', 'Residential', 'Other', 'Residential Surcharge'),
('UPS', 'Residential Surcharge', 'Other', 'Accessorial Surcharge', 'Residential Surcharge', 'Accessorials', 'Residential', 'Other', 'Residential Surcharge'),
('UPS', 'Residential Surcharge Adjustment', 'Other', 'Accessorial Surcharge', 'Other Admin', 'Accessorials', 'Residential', 'Other', 'Residential Surcharge'),
('UPS', 'Return To Sender - Phone Request', 'Other', 'Other / Penalties', 'Returns', 'Other / Penalties', 'Returns', 'Returns', 'Reroute / Intercept'),
('UPS', 'Return To Sender - Web Request', 'Other', 'Other / Penalties', 'Returns', 'Other / Penalties', 'Returns', 'Returns', 'Reroute / Intercept'),
('UPS', 'Returns 2nd Day Air', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', '2nd Day Air', 'Other', 'Returns'),
('UPS', 'Returns 3 UPS Pickup Attempts', 'Other', 'Other / Penalties', 'Returns', 'Base Freight', 'Returns', 'Returns', 'Returns'),
('UPS', 'Returns Delivery Area Surcharge', 'Other', 'Accessorial Surcharge', 'Area Surcharge', 'Base Freight', 'Returns', 'Returns', 'Delivery Area Surcharge'),
('UPS', 'Returns Delivery Area Surcharge - Extended', 'Other', 'Accessorial Surcharge', 'Area Surcharge', 'Base Freight', 'Returns', 'Returns', 'Delivery Area Surcharge Extended'),
('UPS', 'Returns Demand Surcharge - Residential', 'Other', 'Accessorial Surcharge', 'Residential Surcharge', 'Base Freight', 'Returns', 'Returns', 'Demand Surcharge'),
('UPS', 'Returns Electronic Label', 'Other', 'Other / Penalties', 'Returns', 'Base Freight', 'Returns', 'Returns', 'Returns'),
('UPS', 'Returns Fuel Surcharge', 'Other', 'Fuel Surcharge', 'Fuel Surcharge', 'Fuel Surcharge', 'Returns', 'Returns', 'Fuel Surcharge'),
('UPS', 'Returns Ground', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Returns', 'Returns', 'Returns'),
('UPS', 'Returns Next Day Air', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Next Day Air', 'Returns', 'Returns'),
('UPS', 'Returns Print Label', 'Other', 'Other / Penalties', 'Returns', 'Base Freight', 'Returns', 'Returns', 'Returns'),
('UPS', 'Returns Residential Surcharge', 'Other', 'Accessorial Surcharge', 'Residential Surcharge', 'Base Freight', 'Returns', 'Returns', 'Residential Surcharge'),
('UPS', 'Same Day Pickup - Alternate Address - Web Request', 'Other', 'Other / Penalties', 'Miscellaneous', 'Other / Penalties', 'Other Unclassified', 'Other', 'Reroute / Intercept'),
('UPS', 'Saturday Delivery', 'Other', 'Other / Penalties', 'Miscellaneous', 'Other / Penalties', 'Other Unclassified', 'Other', 'Saturday Delivery'),
('UPS', 'Service Charge', 'Other', 'Other / Penalties', 'Other Admin', 'Other / Penalties', 'Other Unclassified', 'Other', 'Service / Admin Fee'),
('UPS', 'Shipping Charge Correction', 'Other', 'Other / Penalties', 'Other Admin', 'Other / Penalties', 'Adjustments', 'Correction', 'Shipping Charge Correction'),
('UPS', 'Shipping Charge Correction 2nd Day Air', 'Other', 'Base Freight', 'Other Admin', 'Base Freight', '2nd Day Air', 'Correction', 'Shipping Charge Correction'),
('UPS', 'Shipping Charge Correction 2nd Day Air A.M.', 'Other', 'Base Freight', 'Other Admin', 'Base Freight', '2nd Day Air', 'Correction', 'Shipping Charge Correction'),
('UPS', 'Shipping Charge Correction 3 Day Select', 'Other', 'Base Freight', 'Other Admin', 'Base Freight', '3 Day Select', 'Correction', 'Shipping Charge Correction'),
('UPS', 'Shipping Charge Correction 3 Day Select Undeliverable Return', 'Other', 'Base Freight', 'Other Admin', 'Base Freight', '3 Day Select', 'Correction', 'Shipping Charge Correction'),
('UPS', 'Shipping Charge Correction Additional Handling', 'Other', 'Accessorial Surcharge', 'Other Admin', 'Other / Penalties', 'Handling & Size', 'Correction', 'Additional Handling'),
('UPS', 'Shipping Charge Correction Additional Handling - Length+Girth', 'Other', 'Accessorial Surcharge', 'Other Admin', 'Other / Penalties', 'Handling & Size', 'Correction', 'Additional Handling'),
('UPS', 'Shipping Charge Correction Addl. Handling longest side', 'Other', 'Accessorial Surcharge', 'Other Admin', 'Other / Penalties', 'Handling & Size', 'Correction', 'Additional Handling'),
('UPS', 'Shipping Charge Correction Addl. Handling second long. Side', 'Other', 'Accessorial Surcharge', 'Other Admin', 'Other / Penalties', 'Handling & Size', 'Correction', 'Additional Handling'),
('UPS', 'Shipping Charge Correction Addl. Handling weight', 'Other', 'Accessorial Surcharge', 'Other Admin', 'Other / Penalties', 'Handling & Size', 'Correction', 'Additional Handling'),
('UPS', 'Shipping Charge Correction Demand Surcharge Addl Handling', 'Other', 'Accessorial Surcharge', 'Other Admin', 'Other / Penalties', 'Handling & Size', 'Correction', 'Demand Surcharge'),
('UPS', 'Shipping Charge Correction Demand Surcharge Large Package', 'Other', 'Other / Penalties', 'Other Admin', 'Other / Penalties', 'Handling & Size', 'Correction', 'Demand Surcharge'),
('UPS', 'Shipping Charge Correction Fuel Surcharge', 'Other', 'Fuel Surcharge', 'Other Admin', 'Fuel Surcharge', 'Fuel Surcharge', 'Correction', 'Fuel Surcharge'),
('UPS', 'Shipping Charge Correction Ground', 'Other', 'Base Freight', 'Other Admin', 'Base Freight', 'Ground', 'Correction', 'Shipping Charge Correction'),
('UPS', 'Shipping Charge Correction Ground Commercial UPS Delivery Intercept Collect', 'Other', 'Base Freight', 'Other Admin', 'Base Freight', 'Ground', 'Correction', 'Shipping Charge Correction'),
('UPS', 'Shipping Charge Correction Ground Return to Sender', 'Other', 'Base Freight', 'Other Admin', 'Base Freight', 'Returns', 'Correction', 'Shipping Charge Correction'),
('UPS', 'Shipping Charge Correction Ground Same Day Pickup- Document', 'Other', 'Base Freight', 'Other Admin', 'Base Freight', 'Ground', 'Correction', 'Shipping Charge Correction'),
('UPS', 'Shipping Charge Correction Ground Undeliverable Return', 'Other', 'Base Freight', 'Other Admin', 'Base Freight', 'Returns', 'Correction', 'Shipping Charge Correction'),
('UPS', 'Shipping Charge Correction Large Package Surcharge - Length + Girth', 'Other', 'Other / Penalties', 'Other Admin', 'Other / Penalties', 'Handling & Size', 'Correction', 'Large Package Surcharge')
ON CONFLICT (carrier, charge_description) DO UPDATE SET
  transportation_mode = EXCLUDED.transportation_mode,
  category_1 = EXCLUDED.category_1,
  category_2 = EXCLUDED.category_2,
  category_3 = EXCLUDED.category_3,
  category_4 = EXCLUDED.category_4,
  category_5 = EXCLUDED.category_5,
  standardized_charge = EXCLUDED.standardized_charge;

INSERT INTO public.master_mapping (carrier, charge_description, transportation_mode, category_1, category_2, category_3, category_4, category_5, standardized_charge)
VALUES
('UPS', 'Shipping Charge Correction Next Day Air', 'Other', 'Base Freight', 'Other Admin', 'Base Freight', 'Next Day Air', 'Correction', 'Shipping Charge Correction'),
('UPS', 'Shipping Charge Correction Next Day Air Early', 'Other', 'Base Freight', 'Other Admin', 'Base Freight', 'Next Day Air', 'Correction', 'Shipping Charge Correction'),
('UPS', 'Shipping Charge Correction Next Day Air Saver', 'Other', 'Base Freight', 'Other Admin', 'Base Freight', 'Next Day Air', 'Correction', 'Shipping Charge Correction'),
('UPS', 'Shipping Charge Correction Third Party Billing Service', 'Other', 'Other / Penalties', 'Other Admin', 'Accessorials', 'Adjustments', 'Correction', 'Shipping Charge Correction'),
('UPS', 'Standard Shipment', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Other Unclassified', 'National', 'International Express'),
('UPS', 'Standard to Canada', 'Parcel', 'Base Freight', 'International', 'Base Freight', 'International', 'International', 'International Express'),
('UPS', 'Surge Fee - Com', 'Other', 'Other / Penalties', 'Peak/Demand', 'Other / Penalties', 'Other Unclassified', 'Other', 'Surge Fee'),
('UPS', 'Surge Fee - Resi', 'Other', 'Other / Penalties', 'Residential Surcharge', 'Other / Penalties', 'Other Unclassified', 'Other', 'Surge Fee'),
('UPS', 'Third Party Billing Service', 'Other', 'Other / Penalties', 'Other Admin', 'Accessorials', 'Other Unclassified', '3rd Party', 'Third Party Billing'),
('UPS', 'Third Party Billing Service Adjustment', 'Other', 'Other / Penalties', 'Other Admin', 'Accessorials', 'Other Unclassified', '3rd Party', 'Third Party Billing'),
('UPS', 'UPS carbon neutral', 'Other', 'Other / Penalties', 'Miscellaneous', 'Other / Penalties', 'Other Unclassified', 'Carbon Neutral', 'Carbon Neutral'),
('UPS', 'Void Declared Value', 'Other', 'Other / Penalties', 'Miscellaneous', 'Other / Penalties', 'Other Unclassified', 'Void', 'Declared Value'),
('UPS', 'Void Delivery Area Surcharge', 'Other', 'Accessorial Surcharge', 'Area Surcharge', 'Accessorials', 'Delivery Area', 'Void', 'Delivery Area Surcharge'),
('UPS', 'Void Demand Surcharge - Residential', 'Other', 'Accessorial Surcharge', 'Residential Surcharge', 'Accessorials', 'Residential', 'Void', 'Demand Surcharge'),
('UPS', 'Void Fuel Surcharge', 'Other', 'Fuel Surcharge', 'Fuel Surcharge', 'Fuel Surcharge', 'Fuel Surcharge', 'Void', 'Fuel Surcharge'),
('UPS', 'Void Ground Commercial', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Ground', 'Void', 'Ground Commercial'),
('UPS', 'Void Ground Commercial Third Party', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Ground', 'Void', 'Ground Commercial'),
('UPS', 'Void Ground Residential Third Party', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Ground', 'Void', 'Ground Residential'),
('UPS', 'Void Residential Surcharge', 'Other', 'Accessorial Surcharge', 'Residential Surcharge', 'Accessorials', 'Residential', 'Void', 'Residential Surcharge'),
('UPS', 'Void Third Party Billing Service', 'Other', 'Other / Penalties', 'Other Admin', 'Accessorials', 'Other Unclassified', 'Void', 'Third Party Billing'),
('UPS', 'Worldwide Expedited', 'Parcel', 'Base Freight', 'International', 'Base Freight', 'International', 'Worldwide', 'International Express'),
('UPS', 'Worldwide Expedited Third Party', 'Parcel', 'Base Freight', 'International', 'Base Freight', 'International', 'Worldwide', 'International Express'),
('UPS', 'Worldwide Express Third Party', 'Parcel', 'Base Freight', 'International', 'Base Freight', 'International', 'Worldwide', 'International Express'),
('UPS', 'Worldwide Saver', 'Parcel', 'Base Freight', 'International', 'Base Freight', 'International', 'Worldwide', 'International Express'),
('UPS', 'Worldwide Saver Shipment Third Party', 'Parcel', 'Base Freight', 'International', 'Base Freight', 'International', 'Worldwide', 'International Express'),
('UPS', 'ZONE ADJUSTMENT 2nd Day Air', 'Other', 'Base Freight', 'Other Admin', 'Base Freight', '2nd Day Air', 'Zone Adjustment', 'Zone Adjustment'),
('UPS', 'ZONE ADJUSTMENT 3 Day Select', 'Other', 'Base Freight', 'Other Admin', 'Base Freight', '3 Day Select', 'Zone Adjustment', 'Zone Adjustment'),
('UPS', 'ZONE ADJUSTMENT Fuel Surcharge', 'Other', 'Fuel Surcharge', 'Other Admin', 'Fuel Surcharge', 'Fuel Surcharge', 'Zone Adjustment', 'Fuel Surcharge'),
('UPS', 'ZONE ADJUSTMENT Ground', 'Other', 'Base Freight', 'Other Admin', 'Base Freight', 'Ground', 'Zone Adjustment', 'Zone Adjustment'),
('UPS', 'ZONE ADJUSTMENT Next Day Air', 'Other', 'Base Freight', 'Other Admin', 'Base Freight', 'Next Day Air', 'Zone Adjustment', 'Zone Adjustment'),
('UPS', 'ZONE ADJUSTMENT Next Day Air Early', 'Other', 'Base Freight', 'Other Admin', 'Base Freight', 'Next Day Air', 'Zone Adjustment', 'Zone Adjustment'),
('UPS', 'ZONE ADJUSTMENT Next Day Air Saver', 'Other', 'Base Freight', 'Other Admin', 'Base Freight', 'Next Day Air', 'Zone Adjustment', 'Zone Adjustment'),
('UPS', 'ZONE ADJUSTMENT Third Party Billing Service', 'Other', 'Other / Penalties', 'Other Admin', 'Accessorials', 'Other Unclassified', 'Zone Adjustment', 'Zone Adjustment'),
('FedEx', 'FedEx 2Day', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', '2nd Day Air', '2nd Day Air Commercial', '2nd Day Air Commercial'),
('FedEx', 'FedEx Express Saver', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Next Day Air', 'Next Day Air Saver Commercial', 'Next Day Air Saver'),
('FedEx', 'FedEx Ground', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Ground', 'Ground Commercial', 'Ground Commercial'),
('FedEx', 'FedEx Home Delivery', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Ground', 'Ground Residential', 'Ground Residential'),
('FedEx', 'FedEx Priority Overnight', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Next Day Air', 'Next Day Air Commercial', 'Next Day Air Commercial'),
('FedEx', 'FedEx Standard Overnight', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Next Day Air', 'Next Day Air Saver Commercial', 'Next Day Air Commercial'),
('WWE', 'Ca Customs Hst', 'Other', 'Other / Penalties', 'Miscellaneous', 'Other / Penalties', 'Other Unclassified', 'Other', 'Customs & Duties'),
('WWE', 'Duty Amount', 'Other', 'Other / Penalties', 'Miscellaneous', 'Other / Penalties', 'Other Unclassified', 'Other', 'Customs & Duties'),
('WWE', 'SMALL PACKAGE FREIGHT', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Ground', 'Ground Commercial', 'Ground Commercial'),
('WWE', 'Delivery Area Surcharge Residential Extended', 'Other', 'Accessorial Surcharge', 'Area Surcharge', 'Accessorials', 'Delivery Area', 'DAS', 'Delivery Area Surcharge Extended'),
('WWE', 'Destination Modifier', 'Other', 'Other / Penalties', 'Other Admin', 'Other / Penalties', 'Adjustments', 'Correction', 'Discount'),
('WWE', 'WEEKLY SERVICE CHARGE', 'Other', 'Other / Penalties', 'Other Admin', 'Other / Penalties', 'Other Unclassified', 'Other', 'Service / Admin Fee')
ON CONFLICT (carrier, charge_description) DO UPDATE SET
  transportation_mode = EXCLUDED.transportation_mode,
  category_1 = EXCLUDED.category_1,
  category_2 = EXCLUDED.category_2,
  category_3 = EXCLUDED.category_3,
  category_4 = EXCLUDED.category_4,
  category_5 = EXCLUDED.category_5,
  standardized_charge = EXCLUDED.standardized_charge;

INSERT INTO public.master_mapping (carrier, charge_description, transportation_mode, category_1, category_2, category_3, category_4, category_5, standardized_charge)
VALUES
('FedEx', 'Add''l Handling-Weight', 'Other', 'Accessorial Surcharge', 'Handling', 'Other / Penalties', 'Handling & Size', 'Additional Handling', 'Additional Handling'),
('FedEx', 'DAS Comm', 'Other', 'Accessorial Surcharge', 'Area Surcharge', 'Accessorials', 'Delivery Area', 'DAS', 'Delivery Area Surcharge'),
('FedEx', 'DAS Commercial', 'Other', 'Accessorial Surcharge', 'Area Surcharge', 'Accessorials', 'Delivery Area', 'DAS', 'Delivery Area Surcharge'),
('FedEx', 'DAS Extended Comm', 'Other', 'Accessorial Surcharge', 'Area Surcharge', 'Accessorials', 'Delivery Area', 'DAS', 'Delivery Area Surcharge Extended'),
('FedEx', 'DAS Extended Resi', 'Other', 'Accessorial Surcharge', 'Area Surcharge', 'Accessorials', 'Delivery Area', 'DAS', 'Delivery Area Surcharge Extended'),
('FedEx', 'Declared Value Charge', 'Other', 'Other / Penalties', 'Miscellaneous', 'Other / Penalties', 'Other Unclassified', 'Other', 'Declared Value'),
('FedEx', 'Demand Surcharge', 'Other', 'Other / Penalties', 'Peak/Demand', 'Other / Penalties', 'Other Unclassified', 'Other', 'Demand Surcharge'),
('FedEx', 'Discount', 'Other', 'Other / Penalties', 'Other Admin', 'Other / Penalties', 'Adjustments', 'Correction', 'Discount'),
('FedEx', 'Earned Discount', 'Other', 'Other / Penalties', 'Other Admin', 'Other / Penalties', 'Adjustments', 'Correction', 'Discount'),
('FedEx', 'Hold for Pickup', 'Other', 'Other / Penalties', 'Miscellaneous', 'Other / Penalties', 'Other Unclassified', 'Other', 'Hold for Pickup'),
('FedEx', 'Performance Pricing', 'Other', 'Other / Penalties', 'Other Admin', 'Other / Penalties', 'Adjustments', 'Correction', 'Discount'),
('FedEx', 'Print Return Label', 'Other', 'Other / Penalties', 'Returns', 'Other / Penalties', 'Returns', 'Returns', 'Returns'),
('FedEx', 'Residential', 'Other', 'Accessorial Surcharge', 'Residential Surcharge', 'Accessorials', 'Residential', 'Other', 'Residential Surcharge'),
('FedEx', 'Return On Call Surcharge', 'Other', 'Other / Penalties', 'Miscellaneous', 'Other / Penalties', 'Other Unclassified', 'Other', 'Reroute / Intercept'),
('FedEx', 'Saturday Pickup', 'Other', 'Other / Penalties', 'Miscellaneous', 'Other / Penalties', 'Other Unclassified', 'Other', 'Saturday Pickup'),
('FedEx', 'Third Party Billing', 'Other', 'Other / Penalties', 'Other Admin', 'Accessorials', 'Other Unclassified', '3rd Party', 'Third Party Billing'),
('FedEx', 'Weekday Delivery', 'Other', 'Other / Penalties', 'Miscellaneous', 'Other / Penalties', 'Other Unclassified', 'Other', 'Service / Admin Fee'),
('FedEx', 'Weekly Service Chg', 'Other', 'Other / Penalties', 'Other Admin', 'Other / Penalties', 'Other Unclassified', 'Other', 'Service / Admin Fee'),
('FedEx', 'Ground', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Ground', 'Ground Commercial', 'Ground Commercial'),
('FedEx', 'Home Delivery', 'Parcel', 'Base Freight', 'Base Freight', 'Base Freight', 'Ground', 'Ground Residential', 'Ground Residential'),
('FedEx', 'Fuel Surcharge', 'Other', 'Other / Penalties', 'Peak/Demand', 'Other / Penalties', 'Other Unclassified', 'Other', 'Fuel Surcharge'),
('FedEx', 'DAS Remote Comm', 'Other', 'Accessorial Surcharge', 'Area Surcharge', 'Accessorials', 'Delivery Area', 'DAS', 'Delivery Area Surcharge Remote'),
('FedEx', 'Late Fee', 'Other', 'Other / Penalties', 'Miscellaneous', 'Other / Penalties', 'Other Unclassified', 'Other', 'Late Fee'),
('FedEx', 'Direct Signature Req.', 'Other', 'Accessorial Surcharge', 'Miscellaneous', 'Accessorials', 'Other Unclassified', 'Other', 'Signature Required')
ON CONFLICT (carrier, charge_description) DO UPDATE SET
  transportation_mode = EXCLUDED.transportation_mode,
  category_1 = EXCLUDED.category_1,
  category_2 = EXCLUDED.category_2,
  category_3 = EXCLUDED.category_3,
  category_4 = EXCLUDED.category_4,
  category_5 = EXCLUDED.category_5,
  standardized_charge = EXCLUDED.standardized_charge;
